name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      python-versions:
        required: false
        type: string
        default: '["3.10", "3.11", "3.12", "3.13"]'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(github.event.inputs.python-versions) }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: latest
    
    - name: Install Wireshark (tshark) - Nightly
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        # Add Wireshark development PPA for latest builds
        sudo add-apt-repository -y ppa:wireshark-dev/stable
        sudo apt-get update
        # Install the latest development version
        sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y tshark
    
    - name: Install dependencies
      run: uv sync --group dev
    
    - name: Verify tshark installation
      run: tshark --version
    
    - name: Run tests
      run: uv run pytest tests/ -v
    
    - name: Run linting
      run: uv run flake8 pcap2har/ tests/
    
    - name: Check formatting
      run: uv run black --check pcap2har/ tests/ 